apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: default
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "https://192.168.13.235/"
      token = "xxxxx"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "default"
        image = "busybox"
